En utilisant numpy:

Ex 1 :Addition
Écrire un programme pour lire les éléments de deux matrices et ajoutez les deux matrices dans la troisième.

La somme de deux matrices de taille (m,n), (A_{ij}) et (B_{ij}) notée A+B  est à nouveau une matrice (C_{ij}) de taille (m,n), obtenue en additionnant les éléments correspondants: $c_{ij}=a_{ij}+b_{ij}$



In [6]:
import numpy as np
 
A = np.array([ [3, 1, 5], [9, 8, -1], [10, 12, 2] ])
B = np.array([ [8, -1, 8], [2, 1, 3], [18, 2, 32] ])
C = A+B

 
print("A :\n", A)
print("B :\n", B)
print("A * B :\n", C)

A :
 [[ 3  1  5]
 [ 9  8 -1]
 [10 12  2]]
B :
 [[ 8 -1  8]
 [ 2  1  3]
 [18  2 32]]
A * B :
 [[11  0 13]
 [11  9  2]
 [28 14 34]]


Ex2 :Multiplication
Écrire un programme pour lire les éléments de deux matrices, puis multipliez les deux matrices dans la troisième.

Deux matrices ne peuvent être multipliées que si le nombre de colonnes de la première matrice est le même que le nombre de lignes de la seconde matrice.

Si $ A=(a_{ij})$ est une matrice de taille (m,n), $ B=(b_{ij})$ et est une matrice de taille (n,p), alors leur produit, noté $AB=(c_{ij})$ est une matrice de taille (m,p) définie par :
$$\forall i,j : c_{ij}=\sum_{k=i}^{n} a_{ik}*b_{kj}$$

In [8]:
import numpy as np
 
A = np.array([ [3, 1, 5], [9, 8, -1], [10, 12, 2] ])
B = np.array([ [8, -1, 8], [2, 1, 3], [18, 2, 32] ])
C = A.dot(B)

 
print("A :\n", A)

print("B :\n", B)
print("A * B :\n", C)

A :
 [[ 3  1  5]
 [ 9  8 -1]
 [10 12  2]]
B :
 [[ 8 -1  8]
 [ 2  1  3]
 [18  2 32]]
A * B :
 [[116   8 187]
 [ 70  -3  64]
 [140   6 180]]


Ex 3: Matrice de Markov

Une matrice de Markov est une matrice carrée dont chaque élément est un réel compris entre 0 et 1 et dont la somme des éléments de chaque ligne vaut 1. Cela correspond, en probabilité, à la matrice de transition d'une chaîne de Markov finie.

Une matrice est dite bistochastique (ou doublement stochastique) si la somme des éléments de chaque ligne et de chaque colonne vaut 1.

1. Ecrire une fonction eststochastique(P) qui permet de vérifier est ce que la matrice P est stochastique ou non
2. Ecrire une fonction estbistochastique(P) qui permet de vérifier est ce que la matrice P est bistochastique ou non
3. Ecrire une fonction vecteurstable(G, h) qui permet de vérifier est ce que h est un vecteur stable de G ou non



In [17]:

import numpy as np

def eststochastique(P):
    nl = len(P)  # nombre de lignes
    nc = len(P[0])  # nombre de colonnes
 
    etat = True  # on suppose que la matrice est stochastique
    for i in range(nl):
        s = 0
        for j in range(nc):
            s += P[i][j]
        if s > 1:
            etat = False
            break
    return etat
 
A = np.array([ [0.5, 0.3, 0.2], [2, 0, -1], [3, 4, -6] ])
eststochastique(A)

True

In [19]:
import numpy as np

def estbistochastique(P):
    nl = len(P)  # nombre de lignes
    nc = len(P[0])  # nombre de colonnes
 
    etat = True  # on suppose que la matrice est bistochastique
    if(eststochastique(P)):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += P[i][j]
            if s > 1:
                etat = False
                break
    return etat
 
A = np.array([ [1, 0, 0], [0, 1, 0], [0, 0, 1] ])
estbistochastique(A)

True

In [21]:

def vecteurstable(G, h):
    nl = len(G)  # nombre de lignes
    nc = len(G[0])  # nombre de colonnes
    etat = True
    if(eststochastique(G)):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += h[i]*G[i][j]
            if s != h[j]:
                etat = False
                break
    else:
        etat = False
    return etat



Ex 4: Transposer

Programmer une fonction qui, étant donné une matrice à deux dimensions A, retourne lamatrice B dont la première colonne est la première ligne de A, la seconde la deuxième ligne de A, etc. B s’appelle la transposée de A.

In [11]:
import numpy as np
 
A = np.array([ [3, 1, 5], [9, 8, -1], [18, 12, 2] ])
 
C = A.transpose()
 
print("A :\n", A)
print("\nTransposée de A :\n", C)

A :
 [[ 3  1  5]
 [ 9  8 -1]
 [18 12  2]]

Transposée de A :
 [[ 3  9 18]
 [ 1  8 12]
 [ 5 -1  2]]


Ex 5: Permutations
1. $M$ désignant une matrice quelconque d’entiers à $l_i$ lignes et $co$ colonnes, $n$ un entier quelconque, programmer une fonction qui retourne la matrice $Sortie$ qui empile verticalement les $co+1$ matrices obtenues en adjoignant à $M$ une colonne $A$ à $li$ lignes dont tousles éléments sont égaux à $n$, $A$ étant placée d’abord devant $M$, puis entre la première et deuxième colonne de $M^a$,etc, jusqu’à ce que $A$ devienne sa dernière colonne. La matriceobtenue  aura $co+1$ colonnes et $(n+1)$ $li$ lignes

2. Écrire toutes les permutations de(1, ..., n)